# Generated by Django 3.1.5 on 2021-05-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doge', '0002_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doge.link')),
            ],
        ),
    ]
