# Generated by Django 3.1.5 on 2021-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doge', '0003_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='error', max_length=1000),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(default='error', max_length=1000),
        ),
    ]
