# Generated by Django 3.1.5 on 2021-05-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doge', '0004_auto_20210515_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(default='Link title', max_length=1000),
        ),
    ]
